server:
  port: 10909
knife4j:
  enable-aggregation: true
  nacos:
    enable: true
    service-url: ttp://192.168.0.106:8848/nacos/
    routes:
      - name: 订单服务
        service-name: user-service
        group-name: DEFAULT_GROUP
        namespace-id: 29708712-1f65-488e-965a-acd5adea43fe
        location: /v3/api-docs?group=default