  datasource: # mysql?????
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ujs_assistant?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 123456