server:
  port: 8810
spring:
  application:
    name: gateway-admin  # nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # 服务注册中心地址
        namespace: 29708712-1f65-488e-965a-acd5adea43fe
        username: nacos
        password: nacos
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
#        - id: shopcart-service
#          uri: lb://shopcart-service
#          predicates:
#            - Path=/api/shopcart/**
#          filters:
#            - SwaggerHeaderFilter
#            - StripPrefix=2
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            - Path=/api/user/**
#          filters:
#            - SwaggerHeaderFilter
#            - StripPrefix=2
nacos:
  gateway:
    route:
      config:
        data-id: gateway-router
        group:   DEFAULT_GROUP