spring:
  cloud:
    nacos:
      gateway:
        routes:
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/api/user/**
            filters:
              - StripPrefix=2