server:
  port: 8100 # ????

spring:
  profiles:
    active: dev # ????
  application:
    name: user-service # ???
  datasource: # mysql?????
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall_user?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # 服务注册中心地址
        namespace: 29708712-1f65-488e-965a-acd5adea43fe
        username: nacos
        password: nacos
  redis:
    jwt : bf5201314
    # Redis默认情况下有16个分片(库)，这里配置具体使用的分片，默认是0
    database: 0
    # redis服务器地址（填写自己的服务器地址）
    host: 127.0.0.1
    # redis端口（默认6379）
    port: 6379
    #redis连接超时等待,10秒
    timeout: PT10S
    # redis访问密码（默认为空）
    password:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 50
        # 连接池中的最大空闲连接 默认 8
        max-idle: 20
        # 连接池中的最小空闲连接 默认 0
        min-idle: 1
        # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认 -1，这里配置10s
        max-wait: PT10S
mybatis-plus: #mybatis
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/svmall/user/mapper/xml/*.xml
  #定时任务
task:
  switch:
    is-open: false #开关
  corn:
    task-corn: 0 48 21 * * ? #定时任务时间格式
