server:
  port: 8010
spring:
#  profiles:
#    active: dev # ????
  application:
    name: user-service # ???
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # 服务注册中心地址
        namespace: 29708712-1f65-488e-965a-acd5adea43fe
        username: nacos
        password: nacos