server:
  port: 8020
spring:
  application:
    name: shopcart-service
  datasource: # mysql?????
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall_user?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # ????????
        namespace: 29708712-1f65-488e-965a-acd5adea43fe
#        username: nacos
#        password: nacos
